# Github link
url = "https://github.com/manoja328/trojaillm2024"

import subprocess
import re

process = subprocess.Popen(["git", "ls-remote", url], stdout=subprocess.PIPE)
stdout, stderr = process.communicate()
sha = re.split(r"\t+", stdout.decode("ascii"))[0]
print(sha)

template = {}
template["ngrams"] = {
    "description": "The ngram to try.",
    "type": "integer",
    "minimum": 3,
    "maximum": 5,
    "suggested_minimum": 3,
    "suggested_maximum": 5,
}


meta_schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "SRI Trinity Framework",
    "technique": "SRI NLP pipeline",
    "technique_description": "We are looking at the confidence scores of tokens generated by the model when triggers are added",
    "technique_changes": "Some bug fixes on inferencing and loss calculation",
    "technique_type": ["Trigger Inversion"],
    "commit_id": sha,
    "repo_name": url,
    "required": [],
    "additionalProperties": False,
    "type": "object",
    "properties": template,
}

params = {}
for k in template:
    params[k] = 2

import json

with open("metaparameters_schema.json", "w") as f:
    json.dump(meta_schema, f)

with open("metaparameters.json", "w") as f:
    json.dump(params, f)

print("Metaparameters generated and saved.....")
